### ISSUE TITLE
Task 2 _  a cleaner approach

### ISSUE THREAD

**Issue by KimboGilda** [bettinaputzi/excercises-week2#2]
https://github.com/bettinaputzi/excercises-week2/blob/6c57aa0e243083f31770ca8f71117ce7dd897212/week2-rexercise_bettinaputzi.R#L73-L78

The task was correctly done, but I just wanted to show you below a cleaner way to it

```
wildschwein_BE <- wildschwein_BE %>%
group_by(TierID) %>%
mutate(
steplength = sqrt((E-lead(E))^2+(N-lead(N))^2)
)

# computing speed
wildschwein_BE <- wildschwein_BE %>%
group_by(TierID) %>%
mutate(
speed = steplength/timelag
)
```

**Comment by bettinaputzi** [comment]
thanks, yea this is cleaner :)
