### ISSUE TITLE
plots _ cleaner

### ISSUE THREAD

**Issue by KimboGilda** [bettinaputzi/excercises-week2#3]
https://github.com/bettinaputzi/excercises-week2/blob/6c57aa0e243083f31770ca8f71117ce7dd897212/week2-rexercise_bettinaputzi.R#L136-L141

Again nice work! I just attach you below a more compact way for creating your plots.

e.g 1-3 comparison

```
ggplot() +
geom_point(data = caro60, aes(E,N, colour = "1 minute"), alpha = 0.2) +
geom_path(data = caro60, aes(E,N, colour = "1 minute"), alpha = 0.2) +
geom_point(data = caro60_3, aes(E,N, colour = "3 minutes")) +
geom_path(data = caro60_3, aes(E,N, colour = "3 minutes")) +
labs(color="Trajectory", title = "Comparing original- with 3 minutes-resampled data") +  theme_minimal()
```

**Comment by bettinaputzi** [comment]
thanks, I had some issues here, I didn't figure out that I don't have to define data already in ggplot() but could also just define it in every geom... that helps 👍
